"use client";

import { useAuth } from "@/contexts/AuthContext";
import { api } from "@/lib/api";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import LoadingSpinner from "@/components/LoadingSpinner";

export default function LandingPage() {
  const { user, loading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && user) {
      if (user.has_profile) {
        router.push("/dashboard");
      } else {
        router.push("/onboarding");
      }
    }
  }, [user, loading, router]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <LoadingSpinner size="lg" text="Loading..." />
      </div>
    );
  }

  const handleStravaLogin = () => {
    window.location.href = api.getStravaLoginUrl();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-marathon-primary to-marathon-secondary">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <div className="pt-20 pb-16 text-center lg:pt-32">
          <h1 className="text-4xl font-extrabold text-white sm:text-5xl md:text-6xl">
            <span className="block">Marathon Training</span>
            <span className="block text-marathon-accent">Made Simple</span>
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-xl text-blue-100">
            Connect with Strava, set your goal, and get a personalized
            AI-powered training plan. Track your progress all the way to the
            finish line.
          </p>

          <div className="mt-10">
            <button
              onClick={handleStravaLogin}
              className="inline-flex items-center px-8 py-4 border border-transparent text-lg font-semibold rounded-lg text-white bg-strava-orange hover:bg-strava-orange-dark transition-colors shadow-lg hover:shadow-xl"
            >
              <svg
                className="w-6 h-6 mr-3"
                viewBox="0 0 24 24"
                fill="currentColor"
              >
                <path d="M15.387 17.944l-2.089-4.116h-3.065L15.387 24l5.15-10.172h-3.066m-7.008-5.599l2.836 5.598h4.172L10.463 0l-7.01 13.828h4.171" />
              </svg>
              Sign in with Strava
            </button>
          </div>
        </div>

        {/* Features Section */}
        <div className="pb-20">
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 text-center">
              <div className="w-16 h-16 bg-marathon-accent rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">🎯</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                Set Your Goal
              </h3>
              <p className="text-blue-100">
                Enter your race date and target finish time. We&apos;ll create a plan
                tailored to your fitness level.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 text-center">
              <div className="w-16 h-16 bg-marathon-accent rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">🤖</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                AI-Powered Plans
              </h3>
              <p className="text-blue-100">
                Get a week-by-week training plan generated by AI, with daily
                workouts designed to get you to the finish line.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 text-center">
              <div className="w-16 h-16 bg-marathon-accent rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">📊</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                Track Progress
              </h3>
              <p className="text-blue-100">
                Sync your runs from Strava and track your progress against the
                training plan.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
