'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { authApi } from '@/lib/api';
import LoadingSpinner from '@/components/LoadingSpinner';

export default function Home() {
  const router = useRouter();
  const { isLoading, isAuthenticated, user } = useAuth();
  const [isRedirecting, setIsRedirecting] = useState(false);

  useEffect(() => {
    if (!isLoading && isAuthenticated) {
      setIsRedirecting(true);
      if (user?.has_profile) {
        router.push('/dashboard');
      } else {
        router.push('/onboarding');
      }
    }
  }, [isLoading, isAuthenticated, user, router]);

  const handleStravaLogin = () => {
    window.location.href = authApi.getStravaAuthUrl();
  };

  // Show loading on same background as landing page to prevent flash
  if (isLoading || isRedirecting) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-orange-50 to-orange-100">
        <LoadingSpinner size="lg" message={isRedirecting ? "Redirecting..." : "Loading..."} />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-orange-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <div className="flex flex-col items-center justify-center min-h-screen text-center py-20">
          <div className="mb-8">
            <span className="text-6xl">🏃</span>
          </div>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-gray-900 mb-6">
            Marathon Training
            <span className="block text-orange-600">Tracker</span>
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mb-10">
            Get an AI-powered personalized training plan for your marathon. Sync your runs from Strava and track your progress to race day.
          </p>

          <button
            onClick={handleStravaLogin}
            className="inline-flex items-center px-8 py-4 border border-transparent text-lg font-semibold rounded-full text-white bg-[#FC4C02] hover:bg-[#E34402] transition-colors shadow-lg hover:shadow-xl"
          >
            <svg className="w-6 h-6 mr-3" viewBox="0 0 24 24" fill="currentColor">
              <path d="M15.387 17.944l-2.089-4.116h-3.065L15.387 24l5.15-10.172h-3.066l-2.084 4.116z" />
              <path d="M10.293 13.828l-2.61-5.172h3.728l2.611 5.172h-3.729z" opacity="0.6" />
              <path d="M7.683 8.656L4.5 2h3.728l3.183 6.656H7.683z" />
            </svg>
            Connect with Strava
          </button>

          {/* Features */}
          <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl">
            <div className="bg-white rounded-xl p-6 shadow-md">
              <div className="text-3xl mb-4">🤖</div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">AI Training Plans</h3>
              <p className="text-gray-600 text-sm">
                Get a personalized week-by-week training plan generated by AI based on your goals.
              </p>
            </div>
            <div className="bg-white rounded-xl p-6 shadow-md">
              <div className="text-3xl mb-4">📊</div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Strava Integration</h3>
              <p className="text-gray-600 text-sm">
                Automatically sync your runs from Strava and track your progress in real-time.
              </p>
            </div>
            <div className="bg-white rounded-xl p-6 shadow-md">
              <div className="text-3xl mb-4">🎯</div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Goal Tracking</h3>
              <p className="text-gray-600 text-sm">
                Set your race date and goal time, and watch your training progress unfold.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
